### ISSUE TITLE
Issue 1: User can view a gallery of national park images

### ISSUE THREAD

**Issue by wang-lawrence** [wang-lawrence/Park-Hopper#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view a gallery of all national park images

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The web app will load the images from all national parks

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://github.com/wang-lawrence/ajax-project/assets/130196412/04a82319-a8be-4289-9c2a-261b96ed5699)
![image](https://github.com/wang-lawrence/ajax-project/assets/130196412/3d1de85b-ff41-4d44-9233-01a5d0355357)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create the HTML for the header/banner so it matches the wireframe
- [x] Add a `div[data-view="gallery"]` to the html
- [x] Complete the layout of the gallery view with HTML and CSS
  - [x] Start with mobile view first
  - [x] Adapt the view to desktop
- [x] Create a `div[class = gallery-container]` to hold the images
- [x] Create a new XMLHttpRequest() to request parks data on all parks from the NPS API /parks endpoint: `https://developer.nps.gov/api/v1/parks`
- [x] Create a `nationalParks` object to hold only objects with a `designation` of "National Park"
- [x] Add an event listener when the data is finished loading and loop through `nationalParks` to: 
  - [x] Create a DOM `div` element to hold an image and an `img` element
  - [x] Call the `images` property and subsequently call the `url` property to access the url of each image
  - [x] Assign the source of the `img` element to the url property 
  - [x] Assign a `data-park-name` attribute to the `div` element and assign it the name of the park
  - [x] Append the `img` element to the `div` element, and append the `div` element to the `gallery-container`
