### ISSUE TITLE
Issue 2: User can filter images based on state and/or activity

### ISSUE THREAD

**Issue by wang-lawrence** [wang-lawrence/Park-Hopper#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can filter images based on state and/or activity

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The State button will display the state abbreviations for all states. The Activity button will display all available activities at all national parks. The user can select the desired state and the images will populate with only parks from that state. The user can select the desired activity and the images will populate with only parks with that activity. The user can also select a state and an activity to filter down more. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
Wireframes identical to issue 1

<img width="790" alt="image" src="https://github.com/wang-lawrence/ajax-project/assets/130196412/efccc043-bb28-4483-bb87-9c36cad9816c">
<img width="274" alt="image" src="https://github.com/wang-lawrence/ajax-project/assets/130196412/6c02242b-c4ac-412d-9621-bcaf9c77883a">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create an array of activities from `nationalParks.states` for each park, this list will be used as filter options for the Where to Go dropdown menu
- [x] Sort the array alphabetically 
- [x] Loop through the array and, create an `option` element for the array item and append the element to the Where to Go dropdown menu
- [x] Create an array of activities from `nationalParks.activities` for each park, this list will be used as filter options for the What to Do dropdown menu
- [x] Sort the array alphabetically 
- [x] Loop through the array and, create an `option` element for the array item and append the element to the What to Do dropdown menu
- [x] Add an event listener to the State button and one to the Activity button to listen for the input event
- [x] Create an event handler so that when the drop down values are changed:
  - [x] Create a new object from `nationalParks` that holds the park data objects that match the State and Activity selected
  - [x] Loop through the new object and create `div` and `img` elements that assign them to the image url similar to the loop described above that was used to iterate through the `nationalParks` object and append them to the `gallery-container`
 
## Stretch Features
- [ ] User can select multiple states and activities 
- [ ] Activities list will dynamically update to only include available activities in the selected State and vice versa.
