### ISSUE TITLE
Issue 3: User can select an image and view more details about the park

### ISSUE THREAD

**Issue by wang-lawrence** [wang-lawrence/Park-Hopper#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="771" alt="image" src="https://github.com/wang-lawrence/ajax-project/assets/130196412/5abff7d8-4714-4036-9192-27f355791e0e">
<img width="204" alt="image" src="https://github.com/wang-lawrence/ajax-project/assets/130196412/dee2efe1-a612-40cb-b1f6-573e249f10b2">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create a `div` with the data-view = 'park-details' attribute 
- [x] Create matching layout to the Figma using CSS and HTML
- [x] Create a `click` event listener on the `gallery-container` div to catch any clicks on the images
- [x] Create a click event handler to:
   - [x] Hide the `gallery-container` view  and show the `park-details` view
   - [x] Create a variable to hold the value of the 'data-park-name' attribute of the image
   - [x] Loop through the `nationalParks` and retrieve the selected park using `nationalParks.fullName`, hold that object in a new variable called `selParkObj`
   - [x] Select the DOM element of the header, the description, the activities, and give them the appropriate `textContent` using the newly created object
   - [x] The header should be in an `<a>` tag and reference the nps webpage for the park
   - [x] Select the DOM element that holds the images and create `img` elements and assign the `src` attribute to the image urls in the object
- [x] Create a `click` event for the back button
- [x] Create an event handler to return to the gallery view by hiding the details view and showing the gallery view
