### ISSUE TITLE
Issue 4: User can save parks to a favorites list

### ISSUE THREAD

**Issue by wang-lawrence** [wang-lawrence/Park-Hopper#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can save parks to their favorites list

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When viewing the park details, user can click on the heart icon to save the park to their favorites list

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="774" alt="image" src="https://github.com/wang-lawrence/ajax-project/assets/130196412/618cd5fc-1d72-410b-a98b-16caceb87a22">
<img width="200" alt="image" src="https://github.com/wang-lawrence/ajax-project/assets/130196412/14e237b3-28d4-4b0a-b43f-e35675a9c007">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add a `div` with `[data-view="saved-parks"]` to show the list of saved parks
- [x] Create layout in HTML and CSS that match the Figma
- [x] Create an object called `data` with the property `currentPark`, this will be used to store the current park `selParkObj` object that is being viewed, 
- [x]  Add a property `savedParks` to `data` and set it as an empty array, this array will store all the saved parks object
- [x] We need to add a functionality to save to a favorites list: 
   - [x] Add code to  the `showParkDetail` function to set the `current-park` value to the `selParkObj`
   - [x] Add a `click` event listener to the heart icon in the park details view
   - [x] Create an event handler to add name of the `currentPark` object to the 'savedParks` array
   - [x] Also add one image url as the `savedParksImg` property value in the `savedParks` object, this will be used as the featured photo in the favorites list
   - [x] Toggle on and off the `font-bold` class for the heart icon
- [x] Add the saved park to the DOM tree in the 'saved-parks' view
  - [x] In the event handler above, create a `div` element for the saved-park card
  - [x] create an `img` element with the `src` attribute assigned the url in the `saved-parks` object and `alt` set to the name of the image and `data-park-name` attribute with the value set to `data.currentPark.name`
  - [x] create a `p` element and set the textContent to the `fullName` of the park and `data-park-name` attribute with the value set to `data.currentPark.name`
  - [x] append the `img` and `p` to the `div`
  - [x] append `div` to the `<div [data-view="saved-parks"]>`
- [x] Add an event listener to `saved-parks-img-container` and call the `showParkDetail` function as the event handler callback
